import dotenv from 'dotenv';
import { createPropertySubmission } from './src/services/createPropertySubmission.ts';

dotenv.config({ path: './.env' });

const payload = {
  agent_user_id: 'real-test-user',
  agent_name: 'Real Tester',
  agent_email: 'real.tester@example.com',
  cover_file_name: 'cover.jpg',
  'Tipo de Inmueble': 'Casa',
  'Operación': 'Venta',
  Dormitorios: 3,
  Ambientes: 5,
  Precio: 150000,
  Expensas: 10000,
  Moneda: 'Pesos',
  'Apto crédito': true,
  Escritura: true,
  'Unidad en Pozo': false,
  Cartel: false,
  Propietario: 'Prop-TEST',
  'Asesor comercial': 'Asesor-Test',
  Productor: 'Productor-Test',
  Sucursal: 'Sucursal-Test',
  Pais: 'Argentina',
  Provincia: 'Buenos Aires',
  Localidad: 'Mar del Plata',
  Barrio: 'Playa Grande',
  Calle: 'Av. Colón',
  'Número': '1234',
  'Piso | Mza | Denominacion': 'Piso 2',
  'Depto | Lote |': 'Depto A',
  Referencia: 'Frente a parque',
  'Baños': 2,
  Plantas: 1,
  Antiguedad: 5,
  'Estado general': 'Excelente',
  'Apto para': 'Familias',
  Estilo: 'Moderno',
  Orientacion: 'Noroeste',
  'Sup Terreno | Hectáreas': '500',
  'Sup Terraza': '20',
  'Sup Balcon': '10',
  'Otras superficies': '30',
  'Metros cubiertos': '120',
  'Sup de Jardin': '100',
  'Mts de Frente': '10',
  'Mts de Fondo': '50',
  Llaves: '2',
  'Descrp. de dormitorio 1': 'Suite principal con baño',
  'Descrp. de dormitorio 2': '',
  'Descrp. de dormitorio 3': '',
  'Descrp. de dormitorio 4': '',
  'Descrp. de dormitorio 5': '',
  Garage: true,
  'Living Comedor': true,
  'Cocina Comedor': true,
  'Comedor diario': true,
  'Ante Cocina': false,
  Dependencias: false,
  Patio: true,
  Pileta: true,
  Hogar: true,
  'Area de parrilla': true,
  Quincho: false,
  'Suite Principal': true,
  Vestidor: false,
  'Sala estar': true,
  Estudio: false,
  Escritorio: false,
  Lavadero: true,
  'Hall acceso': true,
  'Hall distrib.': true,
  'Gas Natural': true,
  'Gas en tubos': false,
  Cloacas: true,
  Sotano: false,
  Bodega: false,
  Despensa: false,
  'Play room': false,
  Bar: false,
  'Jardín inv.': true,
  'Cámara Sept.': true,
  'Galería': false,
  Altillo: false,
  Terraza: true,
  'Aire A.Central': false,
  'Aire A. Ind.': true,
  Calefactores: true,
  'Calef. central': false,
  'Tiro balanc.': false,
  'Calefón': true,
  Estractor: false,
  Termotanque: true,
  Alarma: true,
  'Agua cte.': true,
  Toillette: true,
  Hidromasaje: false,
  Jacuzzi: false,
  Balcon: true,
  Observaciones: 'Prueba de envío real desde backend.',
  'Notas Privadas': 'Test interno',
  Titulo: 'Prueba de Casa Real',
  Detalle: 'Detalle alternativo para portales.',
};

(async () => {
  try {
    const result = await createPropertySubmission(payload as any, []);
    console.log('RESULT', JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('ERROR', error);
    process.exit(1);
  }
})();
