import { validatePropertyPayload } from './src/services/validatePropertyPayload.ts';
import { mapToSheetRow } from './src/mappers/sheetRowMapper.ts';

const payload = {
  agent_user_id: 'u',
  agent_name: 'n',
  agent_email: 'e@example.com',
  cover_file_name: '',
  'Tipo de Inmueble': 'Departamento',
  'Operación': 'Alquiler',
  Dormitorios: 0,
  Ambientes: 0,
  Precio: 0,
  Expensas: 0,
  Moneda: '',
  'Apto crédito': false,
  Escritura: false,
  'Unidad en Pozo': false,
  Cartel: false,
  'Barrio cerrado': false,
  Amoblado: false,
  Ascensor: false,
  Mascotas: false,
  Propietario: '',
  'Asesor comercial': '',
  Productor: '',
  Sucursal: '',
  'Tipo de contrato': '',
  Pais: 'Argentina',
  Provincia: '',
  Localidad: '',
  Barrio: '',
  Calle: 'Calle 123',
  'Número': '123',
  'Piso | Mza | Denominacion': 'PB 3',
  'Depto | Lote |': '4B',
  Referencia: '',
  'Baños': 0,
  Plantas: 0,
  Antiguedad: 0,
  'Estado general': '',
  'Apto para': '',
  Estilo: '',
  Orientacion: '',
  'Sup Terreno | Hectáreas': '',
  'Sup Terraza': '',
  'Sup Balcon': '',
  'Otras superficies': '',
  'Metros cubiertos': '',
  'Sup de Jardin': '',
  'Mts de Frente': '',
  'Mts de Fondo': '',
  Llaves: '',
  'Descrp. de dormitorio 1': '',
  'Descrp. de dormitorio 2': '',
  'Descrp. de dormitorio 3': '',
  'Descrp. de dormitorio 4': '',
  'Descrp. de dormitorio 5': '',
  Garage: false,
  'Living Comedor': false,
  'Cocina Comedor': false,
  'Comedor diario': false,
  'Ante Cocina': false,
  Dependencias: false,
  Patio: false,
  Pileta: false,
  Hogar: false,
  'Area de parrilla': false,
  Quincho: false,
  'Suite Principal': false,
  Vestidor: false,
  'Sala estar': false,
  Estudio: false,
  Escritorio: false,
  Lavadero: false,
  'Hall acceso': false,
  'Hall distrib.': false,
  'Gas Natural': false,
  'Gas en tubos': false,
  Cloacas: false,
  Sotano: false,
  Bodega: false,
  Despensa: false,
  'Play room': false,
  Bar: false,
  'Jardín inv.': false,
  'Cámara Sept.': false,
  'Galería': false,
  Altillo: false,
  Terraza: false,
  'Aire A.Central': false,
  'Aire A. Ind.': false,
  Calefactores: false,
  'Calef. central': false,
  'Tiro balanc.': false,
  'Calefón': false,
  Estractor: false,
  Termotanque: false,
  Alarma: false,
  'Agua cte.': false,
  Toillette: false,
  Hidromasaje: false,
  Jacuzzi: false,
  Balcon: false,
  Observaciones: '',
  'Notas Privadas': '',
  Titulo: 'Test',
  Detalle: '',
};

const result = validatePropertyPayload(payload);
console.log(JSON.stringify(result, null, 2));
if (!result.success) process.exit(1);
const row = mapToSheetRow(result.data, {
  property_id: 'p1',
  submission_id: 's1',
  created_at: 't',
  agent_name: 'n',
  agent_email: 'e@example.com',
  drive_folder_name: 'f',
  drive_folder_url: 'url',
  media_file_count: 0,
  make_status: 'pending',
  sheets_status: 'ok',
});
console.log('row length', row.length);
console.log('Número index', 10 + 25, 'value', row[10 + 25]);
console.log('Piso | Mza | Denominacion index', 10 + 26, 'value', row[10 + 26]);
console.log('Depto | Lote | index', 10 + 27, 'value', row[10 + 27]);
console.log('first property slice', row.slice(10, 40));
