import { useForm, type UseFormReturn } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { propertySchema, type PropertyFormValues } from '../schemas/propertySchema.ts';

export type PropertyForm = UseFormReturn<PropertyFormValues, unknown, PropertyFormValues>;

export function usePropertyForm(): PropertyForm {
  return useForm<PropertyFormValues, unknown, PropertyFormValues>({
    resolver: zodResolver(propertySchema),
    defaultValues: {
      agent_user_id: '',
      agent_name: '',
      agent_email: '',
      cover_file_name: '',
      'Tipo de Inmueble': '',
      'Operación': '',
      Dormitorios: 0,
      Ambientes: 0,
      Precio: 0,
      Expensas: 0,
      Moneda: '',
      'Apto crédito': false,
      Escritura: false,
      'Unidad en Pozo': false,
      Cartel: false,
  'Barrio cerrado': false,
Amoblado: false,
      Ascensor: false,
      Mascotas: false,
      Propietario: '',
      'Asesor comercial': '',
      Productor: '',
      Sucursal: '',
      Pais: 'Argentina',
      Provincia: '',
      Localidad: '',
      Barrio: '',
      Calle: '',
      Numero: '',
      PisoMzaDenominacion: '',
      DeptoLote: '',
      Referencia: '',
      'Baños': 0,
      Plantas: 0,
      Antiguedad: 0,
      'Estado general': '',
      'Apto para': '',
      Estilo: '',
      Orientacion: '',
      SupTerrenoHectareas: '',
      'Sup Terraza': '',
      'Sup Balcon': '',
      'Otras superficies': '',
      'Metros cubiertos': '',
      'Sup de Jardin': '',
      'Mts de Frente': '',
      'Mts de Fondo': '',
      Llaves: '',
      'Descrp. de dormitorio 1': '',
      'Descrp. de dormitorio 2': '',
      'Descrp. de dormitorio 3': '',
      'Descrp. de dormitorio 4': '',
      'Descrp. de dormitorio 5': '',
      Garage: false,
      'Living Comedor': false,
      'Cocina Comedor': false,
      'Comedor diario': false,
      'Ante Cocina': false,
      Dependencias: false,
      Patio: false,
      Pileta: false,
      Hogar: false,
      'Area de parrilla': false,
      Quincho: false,
      'Suite Principal': false,
      Vestidor: false,
      'Sala estar': false,
      Estudio: false,
      Escritorio: false,
      Lavadero: false,
      'Hall acceso': false,
      'Hall distrib.': false,
      'Gas Natural': false,
      'Gas en tubos': false,
      Cloacas: false,
      Sotano: false,
      Bodega: false,
      Despensa: false,
      'Play room': false,
      Bar: false,
      'Jardín inv.': false,
      'Cámara Sept.': false,
      'Galería': false,
      Altillo: false,
      Terraza: false,
      'Aire A.Central': false,
      'Aire A. Ind.': false,
      Calefactores: false,
      'Calef. central': false,
      'Tiro balanc.': false,
      'Calefón': false,
      Estractor: false,
      Termotanque: false,
      Alarma: false,
      'Agua cte.': false,
      Toillette: false,
      Hidromasaje: false,
      Jacuzzi: false,
      Balcon: false,
      Observaciones: '',
      'Notas Privadas': '',
      Titulo: '',
      Detalle: '',
    },
    mode: 'onSubmit',
    reValidateMode: 'onBlur',
  });
}
