export const MAX_SUBMISSION_PAYLOAD_BYTES = 1_073_741_824;
export const MAX_SUBMISSION_PAYLOAD_LABEL = '1 GB';
export const MAX_SUBMISSION_PAYLOAD_BYTES_DRIVE_LEGACY = 3_800_000;
export const MAX_SUBMISSION_PAYLOAD_LABEL_DRIVE_LEGACY = '3.8 MB';
export const MAX_MEDIA_FILES = 20;
